### ISSUE TITLE
Render view?

### ISSUE THREAD

**Issue by cocowalla** [dcomartin/Nancy.MediatR#2]
This looks great for REST APIs, but as-is can it handle rendering views?

**Comment by dcomartin** [comment]
No.  I don't have anything ATM that would render a view.  Basically Nancy is serializing and returning the response object.  What could be done is in a Post() method, would be to take the response object there and pass it to a view rendering engine (Razor).

Here is an example of post method.

https://github.com/dcomartin/Nancy.MediatR/blob/master/src/Nancy.MediatR.Example/InventoryModule.cs
